### ISSUE TITLE
Registered images do not appear in select

### ISSUE THREAD

**Issue by rugk** [KoharaKazuya/tree-view-background#2]
No matter how (manually entering path/using 'register image' from Ctrl+P) or what (directory/file [jpg/gif]) I register it only shows this when I try to select an image:
![emptyselect](https://cloud.githubusercontent.com/assets/11966684/9887417/d35f53ec-5bef-11e5-8072-79ef88b528df.PNG)

**Comment by KoharaKazuya** [comment]
@rugk 
Thank you for the bug report!
But I was able to reproduce the problem :(

Please make sure that you used Ctrl+**SHIFT**+P for the command palette and inputed 'register image'.

**Comment by rugk** [comment]
> But I was able to reproduce the problem :(

You were able or unable?

> Please make sure that you used Ctrl+SHIFT+P for the command palette and inputed 'register image'. 

I did. (Ctrl+P of course doesn't show the command palette - this was a typing mistake) And when the setting is empty the black background picture with white text 'Use [...] to select your image] (or similar) is even shown correctly.

**Comment by KoharaKazuya** [comment]
@rugk 

> > But I was able to reproduce the problem :(
> 
> You were able or unable?

I can select the registered image.

If you use autohide-tree-view package, select the registered images when the tree view is appearing.
The tree-view-background package has the feature that shows images in the same aspect ratio as the tree view. It may be a cause.

**Comment by rugk** [comment]
I have `autohide-tree-view` installed, but I know tried it with this package disabled and it still only displays me a dark area where I can select nothing.

**Comment by rugk** [comment]
Okay just saw these error messages in the dev console:
![filenotfound](https://cloud.githubusercontent.com/assets/11966684/9976230/0a522dc0-5ede-11e5-86dc-d2cec8991345.PNG)

Based on the file paths which are shown there you probably modify these file paths a bit.
As I'm on Windows slashes like `\` have to be inside of the path and should not be URL-encoded.

**Comment by KoharaKazuya** [comment]
@rugk
I forgot URL conversion! I'll fix in the next version.

**Comment by rugk** [comment]
Nice, that's fixed now :smiley:
