### ISSUE TITLE
Package is automatically disabled when registering image

### ISSUE THREAD

**Issue by rugk** [KoharaKazuya/tree-view-background#5]
STR:
1. Enable `tree-view-background`
2. From the command palette select `register image`
3. Click on register.

What happens: The image is correctly registered, but afterwards the package is disabled. One time after I enabled it again it even did not showed the settings anymore. (until a restart of Atom)

What should happen: Just register the image and do not disable the package.

Maybe this is a consequence of the fix of https://github.com/KoharaKazuya/tree-view-background/issues/4...

**Comment by KoharaKazuya** [comment]
@rugk 
The tree-view-background keeps enable in my Atom after registering image. I have no idea why it happened.

Would you tell me the installed packages in your Atom?
(you can see the packages list by the following command)

``` sh
apm list --installed
```

**Comment by rugk** [comment]
```
[later deleted]
```

But I could not reproduce it again now too...
So maybe just a restart after the update which fixed https://github.com/KoharaKazuya/tree-view-background/issues/4 was needed to fix this issue.

**Comment by KoharaKazuya** [comment]
@rugk 
OK, That's good news.
Tell me please if it happens again.
