### ISSUE TITLE
Only loads once

### ISSUE THREAD

**Issue by caracolmzd** [KoharaKazuya/tree-view-background#8]
The image is only loading on the very first load of Atom.

If I switch projects, or open a second window, or even reload with Ctrl-Shift-F5... I get no background.
Re-selecting or shuffling the background doesn't fix it either.

No messages in the console, but I don't think I've tried in developer mode.

**Comment by KoharaKazuya** [comment]
@ginkgomzd Thank you for your report!
That's right, this package loads only once. I think it is a wrong behavior.

I fixed it. You can get a new version (v0.4.4). Please try it.

**Comment by caracolmzd** [comment]
Looks like it is working now!
Thanks
